### ISSUE TITLE
vtsfe_plots not found

### ISSUE THREAD

**Issue by DermyO** [inria-larsen/activity-recognition-prediction-wearable#1]
Hello!

I tried to use your program, but when I launched "python3 main.py " (following the readme file), I had the following error:

> from vtsfe_plots import VTSFE_Plots
>   ImportError: No module named 'vtsfe_plots

And I didn't find this "vtsfe_plots" modul, can you hep me?  (There is only a "vtsfe.py" function).

@serena-ivaldi @mchaveroche

**Comment by mchaveroche** [comment]
Hello Oriane !

It's a bit odd that file disappeared... I will search for code remnants in my laptop this weekend. In the meantime, could you take a look at the Gitlab repo of this project in the INRIA network to retrieve vtsfe_plots.py ?
